CURDIR		:= $(dir $(realpath $(firstword $(MAKEFILE_LIST))))

PANDOC		:= $(HOME)/bin/pandoc-2.11.2/bin/pandoc
PANDOC_FLAGS	:= \
		-f markdown+hard_line_breaks
PANDOC_CSS	:= default.css

RM		:= rm -rf

%.html: %.md
	$(PANDOC) $(PANDOC_FLAGS) $< -s -c $(PANDOC_CSS) -o $@
